package spaceshuttle.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import spaceshuttle.model.ApiResponse;
import spaceshuttle.model.User;
import spaceshuttle.repository.UserRepository;

@RestController
@RequestMapping(path = "/users") // This means URL's start with /user (after Application path)

public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping("/hello")
    public String hello() {
        return "Greetings from Spring Boot!";
    }

    @GetMapping("/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @RequestMapping("/add/{username},{password}") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@PathVariable("username") String username
            , @PathVariable("password")  String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        User newUser = new User();
        newUser.setUsername(username);
        newUser.setPassword(password);
        userRepository.save(newUser);
        return "Saved";
    }


     /*
        homework
        get user by id
     */
    @GetMapping("/get/{userId}")
    public @ResponseBody
    User getUserById(@PathVariable("userId") Long id){
        return  userRepository.findById(id);
    }


    /*
        homework
        update user by id
     */
    @PutMapping("/update/{userId},{userName},{userPassword}")
    public @ResponseBody
    String updateUserById(@PathVariable("userId") Long id,@PathVariable("userName")String userName,
                        @PathVariable("userPassword")String password){
        User user = userRepository.findById(id);
        user.setUsername(userName);
        user.setPassword(password);
        userRepository.save(user);
        return "Saved";
    }


    /*
        Homework
        Delete User by Id
     */
    @DeleteMapping("/delete/{userId}")
    public ApiResponse delete(@PathVariable Long id){
//        User user = userRepository.findByUserId(id);
        userRepository.delete(id);
        return new ApiResponse();
    }


    @PostMapping// Map ONLY GET Requests
    public @ResponseBody
    User addUser(@RequestBody User newUser) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        return userRepository.save(newUser);
    }
}